function fig = acerca()
%--------------------------------------------------------------------
%--------------------------------------------------------------------
% carga de la mascara para la interfase
load acerca
%--------------------------------------------------------------------
%--------------------------------------------------------------------
% definición de propiedades para la interfase
h0 = figure('Units','points', ...
	'Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'FileName','D:\MATLAB\work\gui\acerca.m', ...
	'PaperPosition',[18 180 576 432], ...
	'PaperUnits','points', ...
	'Position',[24 99 430 206.25], ...
   'Tag','Fig2', ...
   'numbertitle','off',...
   'name','Acerca',...
   'ToolBar','none',...
   'menubar','none');
% --------------------------------------------------------------------
% --------------------------------------------------------------------
% etiquetas pertenecientes a la GUI

h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',20, ...
	'ListboxTop',0, ...
	'Position',[51 161.25 310.5 28.25], ...
	'String','Predicción de demanda a corto plazo', ...
	'Style','text', ...
   'Tag','StaticText1');

h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',20, ...
	'ListboxTop',0, ...
	'Position',[51 144 310.5 26.25], ...
	'String','empleando redes neuronales', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[115 117.25 310.5 30], ...
   'String','tipo backpropagation', ...
   'fontsize',20,...
	'Style','text', ...
   'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontAngle','italic', ...
	'FontSize',14, ...
	'FontWeight','bold', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[125.25 77.25 196.5 18.75], ...
	'String','Ing Cesar Giovanny Acevedo', ...
	'Style','text', ...
	'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
   'ListboxTop',0, ...
   'fontsize',14,...
	'Position',[125.25 40.5 205.5 30], ...
	'String','Colaboración John J Sanabria S', ...
	'Style','text', ...
	'Tag','StaticText2');
%----------------------------------------------------------------------
%----------------------------------------------------------------------
% definición de los botones de acción

h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[172.5 12.75 78 18.75], ...
   'Tag','Pushbutton1',...
   'string','Aceptar',...
   'callback','close');
%-------------------------------------------------------------------
%--------------------------------------------------------------------

if nargout > 0, fig = h0; end
