% definición de la GUI para los ajustes de tasa aprendizaje 
% número de épocas y error

h0=figure;
set(h0,'color',[1 1 1]);
set(h0,'menubar','none');
set(h0,'numbertitle','off');
set(h0,'position',[110 220 600 200]);
set(h0,'name','Ajustes avanzados')
%---------------------------------------------------------------------
%---------------------------------------------------------------------
% leyendas correspondientes a las cajas de edición para toma de datos
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[27.75 127.5 153 15], ...
   'Style','text', ...
   'String','Cantidad de epocas (defecto 2000)',...
   'Tag','StaticText1',...
   'BackgroundColor',[1 1 1]);

h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[25.5 108 154.5 15], ...
   'Style','text', ...
   'string','Objetivo de la red (defecto 0.01)',...
	'Tag','StaticText1',...
   'BackgroundColor',[1 1 1]);

h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[26.25 87.75 153.75 15], ...
   'Style','text', ...
   'string','Rata de aprendizaje (defecto 0.1)',...
	'Tag','StaticText1',...
   'BackgroundColor',[1 1 1]);
% --------------------------------------------------------------------
% --------------------------------------------------------------------
% Captura de la información de las variables
hep = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
   'Position',[198 129 69 15.75], ...
   'Callback','epocas=eval(get(hep,''string''));', ...
	'Style','edit', ...
   'Tag','EditText1');

hg = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
   'Position',[198 110.25 69 15.75], ...
   'Callback','goal=eval(get(hg,''string''));', ...
	'Style','edit', ...
   'Tag','EditText1');

hlr = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[198 88.5 69 15.75], ...
   'Style','edit', ...
   'Callback','lr=eval(get(hlr,''string''));', ...
   'Tag','EditText1');

htm1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
   'Position',[198 72 24 12], ...
   'String',' ', ...
	'Style','popupmenu', ...
   'Tag','PopupMenu1', ...
   'string','1|2|3|4|5',...
   'enable','on',...
   'callback','numc=(get(htm1,''value''));');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[26.25 72 153.75 15], ...
   'Style','text', ...
   'string','Nro capas sección oculta (defecto 5)',...
	'Tag','StaticText1',...
   'BackgroundColor',[1 1 1]);
htmc1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
   'Position',[198 52 35 12], ...
   'String',' ', ...
	'Style','popupmenu', ...
   'Tag','PopupMenu1', ...
   'string','1|2|3|4|5|6|7|8|9|10|11|12|13|14|15',...
   'enable','on',...
   'callback','tmaxc=(get(htmc1,''value''));');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[26.25 52 170 15], ...
   'Style','text', ...
   'string','Tamaño max de las capas (defecto 15)',...
	'Tag','StaticText1',...
   'BackgroundColor',[1 1 1]);
% --------------------------------------------------------------------
% --------------------------------------------------------------------
% Creación de boton de acción

h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[165.75 18 93.75 20.25], ...
   'Tag','Pushbutton1',...
   'string','Aceptar',...
   'callback','close');
% ---------------------------------------------------------------------
% ---------------------------------------------------------------------