function fig = bucle()

load bucle
close all
h0 = figure('Units','points', ...
	'Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'FileName','C:\prediccion\bucle.m', ...
	'PaperPosition',[18 180 576 432], ...
	'PaperUnits','points', ...
	'Position',[162.9 200.5 320 42.25], ...
	'Tag','Fig1', ...
   'ToolBar','none',...
   'menubar','none',...
   'numbertitle','off',...
   'name','carga de datos');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[28.5 5.25 100 18.75], ...
   'Tag','Pushbutton1',...
   'string','Carga de datos nuevos',...
   'callback','close;fid=fopen(''datosentre.txt'',''w'');fclose(fid);a=1;dlmwrite(''findatos.txt'',a,''\t'');clear fid;fid=fopen(''fechasfin.txt'',''w'');fclose(fid);clear fid;a=1;dlmwrite(''selecunid.txt'','''');dlmwrite(''unidades.txt'',a,''\t'');a=1;borrado;dos u1;diainicial=dlmread(''findatos.txt'',''\t'',0,0);diainicial(1,:)=[];dlmwrite(''findatos.txt'',diainicial,''\t''); estad');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[158.5 5.25 100 18.75], ...
   'Tag','Pushbutton1',...
   'string','Agregar datos',...
   'callback','close,borrado;dos u2,estad');
f=dlmread('datosentre.txt','\t',0,0);
tam=size(f);
if tam(1)==0
   set(h1,'enable','off');
end
clc
if nargout > 0, fig = h0; end
